import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import { Spotlight } from "@/components/aceternity/spotlight-new";

export const metadata: Metadata = {
   title: "CG-Editor",
   description: "Generated by NV-Phong",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html
         lang="en"
         className="scrollbar-hide selection:bg"
         suppressHydrationWarning
      >
         <body>
            <ThemeProvider
               attribute="class"
               defaultTheme="pastel-pink"
               enableSystem
               disableTransitionOnChange
               themes={["light", "dark", "pastel-pink"]}
            >
               <Spotlight />
               {children}
            </ThemeProvider>
         </body>
      </html>
   );
}
