import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
   title: "CG-Editor",
   description: "Generated by NV-Phong",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html
         lang="en"
         className="scrollbar-hide selection:bg"
         suppressHydrationWarning
      >
         <body>{children}</body>
      </html>
   );
}
